# Generated by Django 5.2.12 on 2026-04-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
