# Generated by Django 5.2.12 on 2026-03-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
